#!/usr/bin/env bash
#
# Bootstrap git repository state for git-flow initialization.
# This script only handles git initialization concerns.

set -euo pipefail

repo="."
main_branch="main"
allow_init="false"

usage() {
  cat <<'EOF'
Usage: git_bootstrap_repo.sh
  [--repo PATH]
  [--main main]
  [--allow-init true|false]

Actions:
  - Validates git availability and repository path
  - If not a git repo, requires explicit consent via --allow-init=true to run git init
  - If no commits exist, requires explicit consent via --allow-init=true to create first commit
  - Creates project-aware .gitignore only when needed and only if .gitignore is missing
  - Creates bootstrap commit without adding unrelated files
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) repo="${2:-}"; shift 2 ;;
    --main) main_branch="${2:-}"; shift 2 ;;
    --allow-init) allow_init="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "[ERROR] Unknown arg: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$allow_init" in
  true|false) ;;
  *)
    echo "[ERROR] Invalid --allow-init: '$allow_init'. Use true or false." >&2
    exit 2
    ;;
esac

if ! command -v git >/dev/null 2>&1; then
  echo "[ERROR] git not found in PATH." >&2
  exit 1
fi

if ! cd "$repo" 2>/dev/null; then
  echo "[ERROR] Cannot cd into repo path: $repo" >&2
  exit 1
fi

echo "Repo: $(pwd)"

gitignore_created=0

has_glob() {
  compgen -G "$1" >/dev/null 2>&1
}

create_project_gitignore_if_needed() {
  if [[ -f .gitignore ]]; then
    echo "  - keep existing .gitignore"
    return 0
  fi

  local detected=0
  local tmp
  tmp="$(mktemp)"
  {
    echo "# Generated by git_bootstrap_repo.sh (minimal project-aware ignore)"
    echo
    echo "# OS / Editor"
    echo ".DS_Store"
    echo ".idea/"
    echo ".vscode/"
  } >"$tmp"

  if [[ -f package.json || -f package-lock.json || -f pnpm-lock.yaml || -f yarn.lock || -f bun.lockb ]]; then
    detected=1
    cat <<'EOF' >>"$tmp"

# Node / JavaScript
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
coverage/
EOF
  fi

  if [[ -f pyproject.toml || -f setup.py || -f setup.cfg || -f Pipfile || -f poetry.lock || -f requirements.txt ]] || has_glob "requirements-*.txt"; then
    detected=1
    cat <<'EOF' >>"$tmp"

# Python
__pycache__/
*.py[cod]
.venv/
venv/
.pytest_cache/
.mypy_cache/
.ruff_cache/
EOF
  fi

  if [[ -f go.mod ]]; then
    detected=1
    cat <<'EOF' >>"$tmp"

# Go
bin/
.coverprofile
EOF
  fi

  if [[ -f Cargo.toml ]]; then
    detected=1
    cat <<'EOF' >>"$tmp"

# Rust
target/
EOF
  fi

  if [[ -f pom.xml || -f build.gradle || -f build.gradle.kts || -f settings.gradle || -f settings.gradle.kts ]]; then
    detected=1
    cat <<'EOF' >>"$tmp"

# JVM / Gradle / Maven
.gradle/
build/
target/
out/
*.class
EOF
  fi

  if has_glob "*.sln" || has_glob "*.csproj"; then
    detected=1
    cat <<'EOF' >>"$tmp"

# .NET
bin/
obj/
EOF
  fi

  if [[ -f CMakeLists.txt ]]; then
    detected=1
    cat <<'EOF' >>"$tmp"

# CMake
CMakeFiles/
CMakeCache.txt
compile_commands.json
EOF
  fi

  if has_glob "*.tf" || has_glob "*.tfvars" || [[ -f terraform.tfstate ]]; then
    detected=1
    cat <<'EOF' >>"$tmp"

# Terraform
.terraform/
*.tfstate
*.tfstate.*
EOF
  fi

  if [[ "$detected" -eq 0 ]]; then
    rm -f "$tmp"
    echo "  - skip .gitignore creation (no known project/tool markers detected)"
    return 0
  fi

  mv "$tmp" .gitignore
  gitignore_created=1
  echo "  - created .gitignore from detected project markers"
}

create_bootstrap_commit_if_needed() {
  local msg
  msg="chore(repo): initialize repository for git-flow"

  if [[ "$gitignore_created" -eq 1 ]]; then
    git add .gitignore
  fi

  if git diff --cached --quiet; then
    if ! git commit --allow-empty -m "$msg" >/dev/null 2>&1; then
      echo "[ERROR] Failed to create initial commit." >&2
      echo "        Configure git identity and rerun:" >&2
      echo "        git config --global user.name \"Your Name\"" >&2
      echo "        git config --global user.email \"you@example.com\"" >&2
      exit 1
    fi
  else
    if ! git commit -m "$msg" >/dev/null 2>&1; then
      echo "[ERROR] Failed to create initial commit." >&2
      echo "        Configure git identity and rerun:" >&2
      echo "        git config --global user.name \"Your Name\"" >&2
      echo "        git config --global user.email \"you@example.com\"" >&2
      exit 1
    fi
  fi

  echo "  - created initial commit for bootstrap"
}

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if [[ "$allow_init" != "true" ]]; then
    echo "[ERROR] Not inside a git repository." >&2
    echo "        Re-run with explicit consent to initialize git:" >&2
    echo "        scripts/git_bootstrap_repo.sh --repo \"$repo\" --main \"$main_branch\" --allow-init true  (run from skill dir)" >&2
    exit 1
  fi
  echo "Git repo missing; initializing (approved by --allow-init=true)..."
  git init --initial-branch "$main_branch" >/dev/null
fi

if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
  if [[ "$allow_init" != "true" ]]; then
    echo "[ERROR] Repo has no commits yet." >&2
    echo "        Re-run with explicit consent so bootstrap can create first commit:" >&2
    echo "        scripts/git_bootstrap_repo.sh --repo \"$repo\" --main \"$main_branch\" --allow-init true  (run from skill dir)" >&2
    exit 1
  fi
  echo "Bootstrapping first commit (approved by --allow-init=true)..."
  create_project_gitignore_if_needed
  create_bootstrap_commit_if_needed
else
  echo "Git bootstrap: already initialized with commits; no action needed."
fi
